M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu22.04.1} date 2025-02-06T23:59:03-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-06T23:59:03-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0118
%
G90
G05
T1
X5.8235Y-4.684
T2
X5.8215Y-4.8338
M30
